### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by thebeatingroad** [cabrerahector/wordpress-popular-posts#174] opened 2018-01-30 02:09 UTC
Hi there and thanks for your plugin!

I edited the wpp.css file to make the widget match my theme style. After accomplishing what I was looking for (in desktop mode), I realized that in the mobile versions (both tablet and phone, iPad and iPhone) the first line of text of each entry is missing. I tried doing some more changes but nothing worked. Is there any way you can help me? Thank you very much in advance!

**Comment by cabrerahector** [comment] 2018-01-30 02:17
Hey there!

That's more theme territory than WPP related, but sure if you share your site's URL I can take a look and give a few suggestions :) (tomorrow though, it's already past 10 pm where I live.)

**Comment by thebeatingroad** [comment] 2018-01-30 17:46
Hola Héctor!

Thank you very much for your interest!!!
This is the site's url: thebeatingroad.com (still under construction). The last widget in the right sidebar is WPP. It looks good on desktop, but in mobile versions, besides the first line of text missing in each entry, also the space between entries is not right.

I really appreciate your time and help! Muchas gracias!

**Comment by cabrerahector** [comment] 2018-01-30 21:37
Just checked your site using both BrowserStack and Chrome's device emulator.

BrowserStack - iPhone 7 Plus - Google Chrome: https://prnt.sc/i7v3ds (text missing, spacing looks OK)
BrowserStack - Samsung Galaxy S8 - Google Chrome: https://prnt.sc/i7vbwp (same as above)
Windows 10 - Google Chrome - iPhone 7 Plus: https://prnt.sc/i7v3pd (looks OK to me)

Also tested on my Nexus 5 and I saw the same behavior as reported by BrowserStack.

Upon a closer inspection, removing the `overflow: hidden;` property from `.wpp-list li` fixes the invisible text, but then the list gets badly messed up without it. You might want to start from there.

**Off-topic:** Your site has a kinda annoying behavior on Chrome (Windows 10). For some reason, the scrollbar slowly moves itself back up - not sure if it's a bug or if this is intended behavior. If it's the latter, you may want to reconsider it as it's not great for User Experience (eg. I'm reading something and the scroll moves itself up, which interrupts what I'm doing - I might just stop reading and leave the site).

**Comment by thebeatingroad** [comment] 2018-01-30 21:42
Hi and huge thanks for such an amazing answer!

I'll try what you say about the overflow... Let's see what I can do, because I'm a total beginner with all this stuff.

Thank you so much for your off-topic comment. Of course, it's totally unintended, I'll have to fix it. Do you have any ideas why can that happen?

Again, thank you so much for your help!

**Comment by cabrerahector** [comment] 2018-01-30 21:53
> Hi and huge thanks for such an amazing answer!

Don't mention it, it was nothing :)

> Let's see what I can do, because I'm a total beginner with all this stuff.

Don't worry about that. We all are beginners at everything at some point. If you like doing this, just keep trying every day and you'll get better at it before you realize it (plus it's fun and we get paid for it :P)

> Thank you so much for your off-topic comment. Of course, it's totally unintended, I'll have to fix it. Do you have any ideas why can that happen?

No idea, to be honest. Didn't dig that deep into the code since I was ready to go home after posting my previous reply (replying from phone now).

**Comment by thebeatingroad** [comment] 2018-01-31 01:19
Hi and thanks again :)

After quite a while doing my best, I managed to get something decent in desktop and phone (iPhone 5). However, in both versions, after removing the overflow: hidden; a black dot appeared in every enrty (upper left margin in desktop, upper right corner inside thumbnails in phone).

To separate title from category in a way that looks decent in both formats, I had to add two <br> in the post html, which I suspect is quite shabby. I wonder if with CSS I could make the taxonomy start in the line right after the title line.

What remains a mystery to me is the tablet (iPad Air 1) behavior. The spacing is now perfect, but the first line of text is still missing. 

Any help would be greatly appreciated! Thanks!!!

**Comment by cabrerahector** [comment] 2018-02-02 12:22
Hi there!

> However, in both versions, after removing the overflow: hidden; a black dot appeared in every enrty (...)

I'm pretty sure it's the default bullet point from UL lists. It can be removed like this:

```
.wpp li {
    list-style: none;
}
```

> ... I had to add two 
> in the post html ...

I guess you meant two `<br />` tags :P

Well, you can make both elements (title and taxonomy) behave as [block elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) via the 'display' CSS property (eg. `display: block;`).

That way, both elements will occupy the entire "row" (like DIVs do, for example).

> What remains a mystery to me is the tablet (iPad Air 1) behavior. The spacing is now perfect, but the first line of text is still missing.

I'll have another look and get back to you as soon as I can :)

**Comment by thebeatingroad** [comment] 2018-02-02 20:49
Hi Héctor!

Thanks one more time. I really appreciate it! :)

- bullet point: It didn't work in my custom css box (under appearance...) but it did editing the plugin wpp.css :). Works in every browser / device (Firefox, Edge, iPhone 5, iPad Air1)... except for Chrome.

- Title and taxonomy are already block elements. I deleted the two <br> tags from post html and added a padding-top: 8.5%; for taxonomy. Works fine in every browser / device... except for Chrome again!

The tablet version still remains a mystery...

Anyway, thanks again for such detailed help and great interest! 😃

**Comment by cabrerahector** [comment] 2018-02-07 18:04
Hi there!

> bullet point: It didn't work in my custom css box (under appearance...) but it did editing the plugin wpp.css :). Works in every browser / device (Firefox, Edge, iPhone 5, iPad Air1)... except for Chrome.

I don't see the bullet point on Chrome, so I'm guessing you probably managed to fix it somehow.

Regarding the editing of the wpp.css file, you'll want to read [this](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#each-time-wordpress-popular-posts-is-updated-the-wppcss-stylesheet-gets-reset-and-i-lose-all-changes-i-made-to-it-how-can-i-keep-my-custom-css) - better safe than sorry :P

> Title and taxonomy are already block elements. I deleted the two 
tags from post html and added a padding-top: 8.5%; for taxonomy. Works fine in every browser / device... except for Chrome again!

Try adding `<div class="group"></div>` between the title and the taxonomy (and I'd add another one right before the closing `</li>` tag just to be sure).

**Closed** 2018-02-14 12:10 UTC
Labels: question
