### ISSUE TITLE
List of links now in the H3 Tag - Change of CSS with the latest update?

### ISSUE THREAD

**Issue by Yoshi9143** [cabrerahector/wordpress-popular-posts#291] opened 2021-07-04 00:35 UTC
With the latest update of wordpress-popular-posts (5.3.4), we noticed a significant change in the styling. 

Digging into it, it looks like the list of URLs is now in the h3 tag:
![image](https://user-images.githubusercontent.com/160189/124369822-1dbde780-dc3e-11eb-9586-e3c157b34d66.png)

Example here: https://graceandlightness.com/

I do not believe this was the case in the prior version (5.3.3). Is this a potential bug?

**Comment by cabrerahector** [comment] 2021-07-04 00:50
Hi @Yoshi9143,

> Is this a potential bug?

Possibly, yes, as there have been some changes to the way the HTML output is built now to enhance security that might affect some users (see [5.3.4 Release Notes](https://cabrerahector.com/wordpress/wordpress-popular-posts-5-3-improved-php-8-support-retina-display-support-and-more/)) but since I can't reproduce that -the HTML is being rendered normally for me, otherwise I would have noticed it haha- I'll need more details.

For example:

- Widget settings (a screenshot would work).
- Does this still happen with all of the other plugins deactivated?
- Does this still happen if you switch to a different theme?

**Comment by koenige** [comment] 2021-07-04 07:56
It looks like the closing tag is not appended directly behind (</h3>) if you set a value in “Title“. Instead, it is appended at the end of the <aside> element. All settings default, I just re-installed the widget in the side bar and added a title for it. If you leave the title for the widget empty, everything works as expected.

**Comment by simplelife0530** [comment] 2021-07-04 08:14
I did only version-up (5.3.3 --> 5.3.4)

Please back to 5.3.3.

2021年7月4日(日) 16:57 Gustaf Mossakowski ***@***.***>:

**Comment by cabrerahector** [comment] 2021-07-04 13:01
I partially reverted some of the security enhancements changes just now, please let me know if that fixes the issue.

**Comment by Yoshi9143** [comment] 2021-07-04 13:22
Thank you for the quick fix! This does appear to fix the issue. Please let me know if I can provide you with any more details for reproducibility.

Here is the widget setting screenshot:
![image](https://user-images.githubusercontent.com/160189/124386624-48915580-dca9-11eb-8bb1-edf19d8ff9ff.png)
![image](https://user-images.githubusercontent.com/160189/124386628-4f1fcd00-dca9-11eb-9ebf-43939139134a.png)

**Comment by koenige** [comment] 2021-07-04 14:15
Thanks, Hector. Works like before. Thank you for the quick fix (especially on a Sunday!).

**Comment by cabrerahector** [comment] 2021-07-04 14:23
Alright, so it was those changes then. How odd, I tested that many times using different combinations way before releasing version 5.3.4 -precisely thinking that it was a major change- and never had any issues with it.

I guess there's at least an edge use case not directly related to the widget (sidebar settings? something else?) that I didn't take into consideration that caused this mess. 

I'll probably leave that alone, at least for now, as these security enhacements were meant to help clueless users who grant admin privileges to people who could misuse them, but I guess that's not really the plugin's responsibility.

Anyways, this comment became a rant haha. Thanks for reporting back guys, glad to know everything's back to normal.

**Closed by cabrerahector** 2021-07-04 14:23 UTC
