### ISSUE TITLE
Update views count from external app

### ISSUE THREAD

**Issue by dnikola** [cabrerahector/wordpress-popular-posts#229] opened 2019-09-17 19:05 UTC
Hello

I would like to update no of views from external app.

My plan is to create custom endpoint and to pass postID value of post for which we should increment not of post.
Can you tell me what function should i call, used by your plugin so I can just pass an ID of post, so your plugin can take care of rest of process?

Thanks!
Nikola

**Comment by cabrerahector** [comment] 2019-09-17 19:36
Hi @dnikola,

I'm not entirely sure because I haven't tried myself but you should be able to update the views count of your posts/pages from an external app (React, Android/iOS app, etc) via the [REST API](https://developer.wordpress.org/rest-api/). To do so:

1. You need to authenticate your app so it gets write access to the REST API.
2. Once your app has been authenticated it should be able to send `POST` requests to the REST API.

Once you have all that sorted out, then this is what you need:

### URL:
`/wp-json/wordpress-popular-posts/v1/popular-posts`

### Method:
`POST`

### Parameters:
- *wpp_id* (**required**), the post/page/custom-post-type ID.
- *sampling*, whether [Data Sampling](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#data-sampling) is enabled or not on your site (0 = disabled, 1 = enabled).
- *sampling_rate*, the [Sampling Rate](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#what-is-sample-rate-for).
- *_wpnonce*, a valid [WordPress Nonce](https://codex.wordpress.org/Function_Reference/wp_create_nonce) called `_wpnonce` (although I'm not sure it this is even necessary if your app is already authenticated so please give it a try and let me know).

Hope that helps.

**Comment by cabrerahector** [comment] 2019-09-17 19:45
Alternatively, if you already have a custom endpoint then you may want to try doing this instead:

```php
$views_count_update_request = new WP_REST_Request(
    'POST',
    '/wordpress-popular-posts/v1/popular-posts'
);
$params = array(
    'wpp_id' => 'YOUR-POST-ID-HERE'
);
$views_count_update_request ->set_query_params($params);

rest_do_request($views_count_update_request); // returns a WP_REST_Response object
```

**Comment by dnikola** [comment] 2019-09-17 19:47
Hi!
Thanks for your fast replay!

This second post sound like a great solution, let me test and I will let you know!

Nikola

**Comment by arhimed-me-account** [comment] 2019-09-17 22:07
Hi

this is some kind of code we are trying to use

```
add_action('rest_api_init', function () {
  register_rest_route( 'wp/v2/posts/post_views_update', '(?P<postID>\d+)',array(
                'methods'  => 'GET',
                'callback' => 'post_view_update'
      ));
});

function post_view_update($request) {
	$views_count_update_request = new WP_REST_Request(
		'POST',
		'/wordpress-popular-posts/v1/popular-posts'
	);
	$params = array(
		'wpp_id' => $postId
	);
	$views_count_update_request ->set_query_params($params);

	rest_do_request($views_count_update_request); 
}
```

And calling a url like wp-json/wp/v2/posts/post_views_update/889174 put a value in table http://prntscr.com/p7hcso

than i tried to use values like 

```
$params = array(
		'wpp_id' => $postId,
		'sampling' => '1',
		'sampling_rate' => '10'

	);
```

than for each visit post count is update but with value 10 instead of 1, and not every 10th

**Comment by dnikola** [comment] 2019-09-17 22:09
Hi

this is some kind of code we are trying to use

```
add_action('rest_api_init', function () {
  register_rest_route( 'wp/v2/posts/post_views_update', '(?P<postID>\d+)',array(
                'methods'  => 'GET',
                'callback' => 'post_view_update'
      ));
});

function post_view_update($request) {
	$views_count_update_request = new WP_REST_Request(
		'POST',
		'/wordpress-popular-posts/v1/popular-posts'
	);
	$params = array(
		'wpp_id' => $postId
	);
	$views_count_update_request ->set_query_params($params);

	rest_do_request($views_count_update_request); 
}
```

And calling a url like wp-json/wp/v2/posts/post_views_update/889174 put a value in table http://prntscr.com/p7hcso

than i tried to use values like 

```
$params = array(
		'wpp_id' => $postId,
		'sampling' => '1',
		'sampling_rate' => '10'

	);
```

than for each visit post count is update but with value 10 instead of 1, and not every 10th, that is second row on screenshot http://prntscr.com/p7hcso

**Comment by cabrerahector** [comment] 2019-09-17 22:15
That's the expected behavior, @dnikola. See here for more details: [How does Data Sampling work?](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#how-does-data-sampling-work)

Since the original question has been answered already (*Update views count from external app*) I'm closing this issue now. If you have any additional questions don't hesitate to ask.

**Closed by cabrerahector** 2019-09-17 22:15 UTC
Labels: question

**Comment by cabrerahector** [comment] 2019-09-17 22:33
On a second thought, the whole Data Sampling logic isn't handled by the REST API endpoint but by the browser (see [related code](https://github.com/cabrerahector/wordpress-popular-posts/blob/4.2.2/public/js/wpp.js#L57-L72)) so actually it might be a good idea to not use the data sampling parameters in your request or to re-implement the data sampling logic in your custom controller so it mimics the behavior from the JS code.

**Comment by dnikola** [comment] 2019-09-17 23:00
Hector,

thanks for your kind replay!

May I ask you if you can explain me from [this code](https://github.com/cabrerahector/wordpress-popular-posts/blob/4.2.2/public/js/wpp.js#L57-L72) how is calculated sampling rate

for me it looks like it is random :) ?

**Comment by cabrerahector** [comment] 2019-09-17 23:08
No problem. That code basically generates a random number between 1 and *N*, being *N* the Sampling Rate (eg. 10).

If the generated random number is equal to *1* then proceed to update the views count, otherwise don't do anything.

If you want to use Data Sampling for performance reasons, you may want to consider using this solution instead: [Caching Pageviews](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#caching-pageviews).
