### ISSUE TITLE
rest_cookie_invalid_nonce

### ISSUE THREAD

**Issue by Ungov77** [cabrerahector/wordpress-popular-posts#347] opened 2022-12-02 00:40 UTC
Hi, i run the widget with the following cache config:

- Cloudflare page cache with "cache everything" rule + WP plugin CF Super Cache (1 hour expiration)
- W3 Total Cache + Memcached Object Cache (default lifetime 180 seconds)
- W3 Zend Opcache
- W3 Database Cache with Memcached
- W3 Memcached Fragment Cache

But the widget is sometimes returning the Error 403 with message rest_cookie_invalid_nonce
![image](https://user-images.githubusercontent.com/2366002/205186904-60ee6868-10c6-49a2-a345-6fa0f36cdaab.png)

I searched the forum for similar issues and I understand this is due to the nonce expiring after 24 hours, but I'm not sure how to fix it as the default limits seem under the 24 hours threshold

**Comment by cabrerahector** [comment] 2022-12-02 01:33
Hi @Ungov77,

WordPress Popular Posts uses a [nonce](https://codex.wordpress.org/WordPress_Nonces) provided by WordPress as part of the request when communicating with WordPress' [REST API](https://developer.wordpress.org/rest-api/). If by the time the request is sent to the REST API to do whatever WPP needs to do said nonce is no longer valid (eg. it expired because of site caching rules) then you'll get these 403 Forbidden responses from the REST API. There are also some security / firewall plugins thay actively restrict or fully block access to the REST API that can cause 403 HTTP responses from the server.

Going with the information you have provided so far it doesn't seem like you're using a security / firewall plugin (or if you are then the REST API isn't probably being restricted?) and so that leaves caching as the other possible cause (as I sure you already suspect.)

If your page cache is set to expire every 24 hours or less (I'd actually recommend have it expire every 12 hours, I'll explain below and should also update the Wiki to reflect this) then the problem probably lies elsewhere. I say "probably" because of this (from the Nonces documentation link I shared earlier):

> WordPress uses a system with two ticks (half of the lifetime) and validates nonces from the current tick and the last tick. In default settings (24h lifetime) this means that the time information in the nonce is related to how many 12h periods of time have passed since the Unix epoch. This means that a nonce made between midday and midnight will have a lifetime until midday the next day. The actual lifetime is thus variable between 12 and 24 hours.

However I couldn't say if your page cache expiring every 24 hours would be the cause: if your site gets enough traffic to guarantee that nonces expire exactly every 24 hours then it should be fine, otherwise there will be instances where your page cache will render pages where WPP is using expired nonces, leading to this problem.

So, things I'd try if I were you:

- Make sure your page cache expires every 12 hours (I guess this is W3 Total Cache's responsibility), or
- Double check the settings you're using with your other "W3" plugins (I'd have a look at W3 Database Cache first), or
- You could also try upping the lifetime of nonces (eg. 36-48 hours) via the [nonce_life](https://developer.wordpress.org/reference/hooks/nonce_life/) filter hook (but from a security standpoint this might not be a great idea, generally you want nonces to expire _sooner_, not _later_).

Aside from that there's not a lot more I can suggest as this is not something within WPP's control so please do spend some time fine-tuning your settings, make sure that your caching rules (page cache, object cache, etc) are not being too greedy/strict.

If you happen to figure out what's causing this issue please do consider sharing it here as it might help someone else in the future.

If you have any further comments / questions do let me know, alright?

**Comment by cabrerahector** [comment] 2022-12-14 14:03
Closing issue due to inactivity.

OP, if there's anything else I could help with please feel free to leave a comment below.

**Closed by cabrerahector** 2022-12-14 14:03 UTC
Labels: question
