### ISSUE TITLE
v4 throws PHP notices with WP_DEBUG true

### ISSUE THREAD

**Issue by rahulnever2far** [cabrerahector/wordpress-popular-posts#117] opened 2016-09-17 05:20 UTC
`Notice: Undefined index: ajax in PATH_TO\wp-content\plugins\wordpress-popular-posts-wpp4\includes\class-wordpress-popular-posts-widget.php on line 34`

`Notice: Undefined index: css in PATH_TO\wp-content\plugins\wordpress-popular-posts-wpp4\public\class-wordpress-popular-posts-public.php on line 79`

**Comment by cabrerahector** [comment] 2016-09-17 14:22
Hey there!

I was unable to trigger this warning with a freshly installed WordPress, WPPv4 and WP_DEBUG enabled. Did you install v4 on top of v3?

**Comment by rahulnever2far** [comment] 2016-09-17 14:25
I had removed v3 and added v4 in the same WordPress site on localserver.

**Comment by cabrerahector** [comment] 2016-09-17 14:34
Alright, I'll install v3 first, uninstall it (when you say _removed v3_ it means you uninstalled it the standard way, right?), then install v4 and see if I can reproduce this.

**Comment by rahulnever2far** [comment] 2016-09-17 14:37
I didn't uninstall the standard way. I just removed the directory. WordPress disabled it by itself.

**Comment by cabrerahector** [comment] 2016-09-17 15:00
Alright, here's what I tried:

1. Removed v4.
2. Installed v3 from WordPress' repo.
3. Set a few options for the widget.
4. Removed v3 by deleting its folder from the plugins directory.
5. Checked the _Plugins_ page and got the "The plugin wordpress-popular-posts/wordpress-popular-posts.php has been deactivated due to an error: Plugin file does not exist" message from WordPress.
6. Pasted v4 into the plugins directory.
7. Checked the _Plugins_ page and activated v4.

After that, both indexes (_ajax_ and _css_) are defined and no PHP notices are thrown. Anything else I should try?

**Comment by rahulnever2far** [comment] 2016-09-17 15:02
That's weird. I'll try to reproduce it later tonight. Will let you know how it goes.

**Comment by cabrerahector** [comment] 2016-09-17 15:04
Thanks, please keep me posted with your findings.

**Comment by cabrerahector** [comment] 2016-12-14 11:57
Since it's been a while and there hasn't been any updates on this from the OP or someone else I'm closing this topic for the time being.

**Closed by cabrerahector** 2016-12-14 11:57 UTC
Labels: bug
