### ISSUE TITLE
Error with JSON

### ISSUE THREAD

**Issue by estudiohz** [cabrerahector/wordpress-popular-posts#374] opened 2023-11-09 12:33 UTC
## Describe the problem
We are using the plugin on https://www.nintenderos.com/
It works fine until yesterday that started to fail.
Is like is not saving the stadistics

On homepage:
wpp.min.js:7 WPP: Couldn't read JSON data

## Steps to reproduce it

1.When you visit plugin screen of stadisticd console says:
options-general.php:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
options-general.php:1 Uncaught (in promise) Message port was closed before response send
The stadistics are always 0
2.
3.

## Expected behavior
Wordpress to last version.

## Environment

Database version: 10.5.21-MariaDB-1:10.5.21+maria~deb11-log
Versión 6.3.3
WordPress version: 6.4.1
PHP version: 8.0.30
- Active plugins:

**Comment by cabrerahector** [comment] 2023-11-09 12:45
Hola @estudiohz,

The issue is being caused by a change introduced with WordPress 6.4 which affects WordPress themes that don't provide HTML5 support.

Please checkout [Popular Posts disappeared after WP 6.4 update](https://wordpress.org/support/topic/popular-posts-disapeared-after-wp6-4-update/) for more details and a workaround.

**Comment by cabrerahector** [comment] 2023-11-09 18:55
Closing this ticket as it should have been fixed by 128b25d.

**Closed by cabrerahector** 2023-11-09 18:55 UTC

**Comment by estudiohz** [comment] 2023-11-09 19:07
The problem was the html5 supoort
 Thank hector
